<!--
  ~ Eglobe IT Solutions (P)Ltd.
  ~
  ~ @category    Egits
  ~ @package    Egits_GoogleMerchantApi
  ~ @copyright   Copyright (c) 2019 Eglobe IT Solutions. (http://www.eglobeits.com/)
  ~ @author      Eglobe Magento Team <info@eglobeits.com>
  ~
  -->
<?php
/**
 * @var $block \Egits\GoogleMerchantApi\Block\Adminhtml\System\Config\TestConnectionButton
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        function TestMerchantAccountConnection() {
            params = {};
            new Ajax.Request('<?= /* @noEscape */$block->getAjaxUrl() ?>', {
                loaderArea: false,
                asynchronous: true,
                parameters: params,
                onSuccess: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    var messageContainer =  jQuery('#message-test-connection');
                    if (response.error) {
                        messageContainer.removeClass('message message-error')
                            .addClass('message message-error').html(response.message);
                    } else {
                        messageContainer.removeClass('message message-success')
                            .addClass('message message-success').html(response.message);
                    }
                }
            });
        }

        jQuery('#test_connection').click(function () {
            TestMerchantAccountConnection();
        });
    });
</script>

<?= $block->getButtonHtml() ?>
<div id="message-test-connection"></div>