<?php
/**
 *
 *  Eglobe IT Solutions (P)Ltd.
 *
 * @category    Egits
 * @package    Egits_GoogleMerchantApi
 * @copyright   Copyright (c) 2019 Eglobe IT Solutions. (http://www.eglobeits.com/)
 * @author      Eglobe Magento Team <info@eglobeits.com>
 */
?>
<?php
/** @var $block \Egits\GoogleMerchantApi\Block\Adminhtml\Attribute\Template */
?>
<?= $block->getChildHtml('google_merchant_attribute_grid'); ?>
